### ISSUE TITLE
robe-jump returns error file doesnt exists - but it exists

### ISSUE THREAD

**Issue by 99monkey** [dgutov/robe#137]
I have a rails project

```
Api::V1::Firm::Members::IndexSerializer
```

when my cursor under this

then M-x robe-jump 

```
robe-find-file: ’/Users/developer/dev/project/app/serializers/api/v1/firm/members/index_serializer.rb
’ does not exist

```
this file with this absolue path exists and I can jump to it 

other classes like SomeModule::AnyForm finds great
How can I help to investigate it?

**Comment by dgutov** [comment]
Hi!

Am I reading that right that it's trying to visit a file with a newline at the end? Or is that just a side-effect of copying?

**Comment by dgutov** [comment]
Does that file contain any methods? If not:

Check the contents of `$LOADED_FEATURES` in the REPL. Does the file name there look right?

If you like, you can try print-debugging the `full_scan` method, it should be triggered in this scenario: https://github.com/dgutov/robe/blob/master/lib/robe/sash/const_locations.rb#L56-L69

Or you can try producing a minimal reproduction: a sample project which has this problem. And I'll take it from there.

**Comment by 99monkey** [comment]
i made a video with the issue https://youtu.be/R_q7MIx93iM, i've checked $LOADED_FEATURES

**Comment by dgutov** [comment]
Hi again!

Sorry for the late reply.

You examine the value of `$LOADED_FEATURES` near the beginning of the video, and it doesn't have the files in question. But Rails has an autoloading feature: when you access a constant (and module names are constants), the autoloader (most recently, Zeitwerk) can look up existing files in the specified list of directories. So at the end of the scenario the value of this constant should be longer.

But now that I read it again, I see that `full_scan` checks that the feature ends with `.rb` anyway, so it's unlikely that the problem came from that method.

Here's my next guess: one of the methods on `Api::V1::Firm::Members::IndexSerializer` (and `ShowSerializer` as well, apparently) returns such broken value in its `source_location` method.

Try this snippet in the created inf-ruby Rails console with Robe loaded:

```rb
obj = Api::V1::Firm::Members::IndexSerializer

methods = obj.methods(false).map { |m| obj.method(m) } +
          (obj.__instance_methods__(false) +
           obj.private_instance_methods(false)).map { |m| obj.instance_method(m) }

methods.each { |m| puts "#{m}: #{m.source_location&.first}" }
```

**Comment by mrrooijen** [comment]
I just ran into this issue as well. Most files would properly open using `robe-jump` but certain files would not.

Considering the fact that similar files (i.e. other models) do appear to open, I figured that perhaps the problem was with the contents of the file. It turns out that this is the case.

The following file will not open with `robe-jump`.

```rb
class User::CreateInput
end
```

Error (similar to @99monkey):

```
'/Users/michael/dev/poc/app/inputs/user/create_input.rb
' does not exist
```

But the same file containing a single method definition will open as expected:

```rb
class User::CreateInput
  def this_method_definition_fixes_the_problem
  end
end
```

The same applies to the model file.

```rb
class Team < ApplicationRecord
  has_many :memberships
  validates :name, presence: true
  # etc
end
```

Here we have a bunch of class method calls, but no method definitions.

When attempting to open this file using `robe-jump` the following error occurs:

```
'/Users/michael/.gem/rubv/3.1.2/gems/rubocop-1.35.1/lib/rubocop/cop/team.rb
/Users/michael/.gem/ruby/3.1.2/gems/faker-2.23.0/lib/faker/default/team.rb
/Users/michael/dev/poc/app/models/team.rb
'does not exist
```

I want to open app/models/team.rb but it finds three different paths and doesn't open anything.

However, after adding a method definition it appears to work correctly.

```rb
class Team < ApplicationRecord
  has_many :memberships
  validates :name, presence: true
  # etc
  def this_method_definition_fixes_the_problem
  end
end
```

Defining a class method instead of an instance method also fixes the problem (`def self. this_method_definition_fixes_the_problem`).

Thoughts?

**Comment by 99monkey** [comment]
Yes, it's my case too, I guess. Serializer in most cases dont have definition of methods. I should check this out..

**Comment by dgutov** [comment]
If this happens only when the class has no methods of its own, then...

Could you try changing this line in your local installation

https://github.com/dgutov/robe/blob/993ae13791ba882076b644b0c8054b6e89e22dad/lib/robe/sash/const_locations.rb#L63

to `if false` (and maybe commenting out the previous line as well), as see if that fixes the behavior?

**Comment by dgutov** [comment]
Aaand never mind, this should fix that. Apparently BSD Grep assigns different meaning to `-Z`.

Let me know if the problem remains, of course.

**Comment by mrrooijen** [comment]
Yep, that fixed the issue. Thanks!

Is there a way to limit `robe-jump` results to the current project?

`robe-jump` on `Team` yields the following, and then you can just select the desired file:

```
.gem/ruby/3.1.2/gems/rubocop-1.35.1/lib/rubocop/cop/team.rb
.gem/ruby/3.1.2/gems/faker-3.0.0/lib/faker/default/team.rb
dev/poc/app/models/team.rb
```

Not a big deal, but would be nice if it could just assume `app/models/team.rb` rather than the other results.

Thanks for the great package.

**Comment by dgutov** [comment]
Are you sure to want to *limit* it to the current project?

One of the benefits of this package is that it can navigate to gems (Solargraph has more difficulties with that). And it's handy to be able to see an implementation of some library feature from time to time.

What we could try to do though, is to sort the locations during completion so that those inside the project come first.

**Comment by dgutov** [comment]
There's also the issue that in the other two suggestions the fully-qualified name is longer than `Team`, so preprocessing those based on the file contents could work as well.

Anyway, please open a separate issue and we'll continue there.
