### ISSUE TITLE
`*robe-doc*`: optionally show the method source directly

### ISSUE THREAD

**Issue by vemv** [dgutov/robe#145]
## Context

I use Robe with company-mode and `company-auto-update-doc t`.

Many Ruby methods lack comments, so showing their source is the best next option.

By default, `*robe-doc*` shows a `Source` button:

![image](https://github.com/dgutov/robe/assets/1162994/cd15bc4a-829a-45f7-94e4-7779129cf993)

This button is not clickable during a company-mode completion.

(I do not mind about that 'bug' - I don't see myself clicking around during Company completions)

## Request

I wish that users could opt in for the source to be shown during Company completion.

i.e. instead of the button, we render the source directly.

(that is: the source of the method - not that of the entire underlying file)

Robe could go as far as rendering the method source unconditionally if no doc was available.

WDYT?

Thanks - V

**Comment by dgutov** [comment]
That's a good point.

Now added an option which defaults to "show source when there's no doc" (but you could also customize it to `t`). See how you like it.

**Comment by dgutov** [comment]
Also, when I was testing it, it seemed like the blinking of the doc window (even when switching to next completion that's also with a doc) might be annoying. Not sure if it's particular to certain backends (network calls can trigger redisplay). Perhaps it's worth revisiting the mechanism.

And speaking of Robe, maybe we should return `nil` in more cases. Rather than display a fully empty buffer for certain methods (e.g. stdlib when pry-doc is not installed).

**Comment by vemv** [comment]
Working very nicely - thanks so much!

I wish I had something like this during all my Ruby years - would have avoided so much googling.
