### ISSUE TITLE
Randomize port to edit multiple project at once

### ISSUE THREAD

**Issue by ypresto** [dgutov/robe#58]
Currently robe.el uses fixed port to launch robe server.
https://github.com/dgutov/robe/blob/152ed9efd42d653411f04020bb7b7d80b15f7f2c/robe.el#L80
This leads to conflict of listening port when opening multiple project at once.

So it'll be better to randomly pick unused port.
It can be implemented using "port 0" and notifying port from robe server; something like `"robe on 12345"`.
http://stackoverflow.com/a/201528/1474113

**Comment by dgutov** [comment]
That's a great tip. This has been a long-standing issue for me personally, so thanks for the push, too.

We're still limited to one Robe process per Emacs instance (because it's hard to determine, conceptually, which buffers relate to which project when they're outside of its tree, such as files inside gems), but now we can make do with several Emacs instances.

**Comment by ypresto** [comment]
thanks! I'll remove port number setting from atom plugin.
