### ISSUE TITLE
Support complete function arguments template

### ISSUE THREAD

**Issue by stardiviner** [dgutov/robe#72]
I found some complete sources provide function arguments template complete. Like irony. I don't know whether robe can support this, ask here, is it possible?

**Comment by dgutov** [comment]
Shouldn't be too hard.

**Comment by stardiviner** [comment]
Thanks.

**Comment by dgutov** [comment]
I'm not so sure about this feature. With the current completion smarts, we'd be giving the wrong list of arguments a significant percentage of the time because we usually don't know the type of the call target.

Which is different from Irony which only has to deal with statically typed languages and uses the analyzer from Clang.

**Comment by stardiviner** [comment]
Ok, I close this issue.
