### ISSUE TITLE
setting for view-mode with jumps to gems?

### ISSUE THREAD

**Issue by mjhoy** [dgutov/robe#94]
I'm often jumping to the source definition in my rubygems; it would be nice to automatically open these with `view-file` rather than `find-file`. Perhaps there could be a variable to allow this?

I would propose, if the variable is set, checking the path of `file` here: https://github.com/dgutov/robe/blob/master/robe.el#L347 and if it is in a rubygems locations (contains "ruby/gems" or some such) enables view mode after visiting the file.

**Comment by mjhoy** [comment]
here's a draft: https://github.com/mjhoy/robe/commit/2792b2e60b7783c5cdcbeda4d0f7e45f108890c1

**Comment by dgutov** [comment]
Thanks for the request. But why `view-mode` exactly? I'm more inclined to visit them simply in `read-only-mode`. So instead of a variable, maybe we'll have a hook where you could choose what minor mode to use.

But then, are there cases when you *wouldn't* want to open a file within a gem in `view-mode`? Unless there are, maybe you can just use `find-file-hook`.

**Comment by mjhoy** [comment]
Ah! I think `read-only-mode` makes much more sense.

In terms of `find-file-hook`, you are probably right. Although if I'm rooting around in my gems directory, say in dired, there is perhaps a slightly better chance that I actually want to muck around editing files, than if I am coming to a gem from the robe doc mode.

**Comment by dgutov** [comment]
OK, the hook is now there. Since `(string-match-p "ruby/gems" buffer-file-name)` is not a very strict check, I'd rather you have it in your personal configuration. At least for now.

**Comment by mjhoy** [comment]
Thanks!
